
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://popxstrzcqiesobdhbch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcHhzdHJ6Y3FpZXNvYmRoYmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjM4NTgsImV4cCI6MjA2NjE5OTg1OH0.RrKtAwYrlIJX4WY8bKTsK3B7LSyCYzGwTfKtD5R8wE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
